network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp5s0:
      dhcp4: no
      dhcp6: no
      accept-ra: no
  bridges:
    br0:
      interfaces:
        - enp5s0
      dhcp4: yes
      dhcp6: no
      link-local: []
      accept-ra: no
